import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-chemical-feedstock-formula-price-audit",
  "engine": "recovery",
  "title": "Chemical Feedstock Formula-Price Audit",
  "shortTitle": "Chemical Feedstock Formula-Price Audit",
  "tagline": "Quantify, recover, and prevent financial leakage through chemical feedstock formula-price audit",
  "industry": "Chemical Procurement Recovery",
  "uiPort": 4610,
  "apiPort": 5610,
  "accent": "#1d4ed8",
  "currency": "USD",
  "primaryOutcome": "Chemical Feedstock Formula-Price Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect supplier agreements, material grades, commodity indexes, publication dates, formula lags, floors, ceilings, freight differentials, energy surcharges, quality credits, invoices, and rebates in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "billedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Supplier Billed Amount",
    "expectedLabel": "Formula-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Chemical Feedstock Formula-Price Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("supplier-contract-library","CFF01","Supplier contract library","Execute supplier contract library using supplier agreements, material grades, commodity indexes, publication dates, formula lags, floors, ceilings, freight differentials, energy surcharges, quality credits, invoices, and rebates.","Produce a governed supplier contract library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Material Grade","text","Supplier / Material Grade · Standard Case"],["caseReference","Supplier contract library Reference","text","CFF01-2026-001"],["billedAmount","Supplier Billed Amount","currency",771500],["supportedAmount","Formula-Supported Amount","currency",663490],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Supplier contract library case","Material grade registry case","Index source control case","Publication date validation case","Formula price calculation case"]}),
feature("material-grade-registry","CFF02","Material grade registry","Execute material grade registry using supplier agreements, material grades, commodity indexes, publication dates, formula lags, floors, ceilings, freight differentials, energy surcharges, quality credits, invoices, and rebates.","Produce a governed material grade registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Material Grade","text","Supplier / Material Grade · Standard Case"],["caseReference","Material grade registry Reference","text","CFF02-2026-001"],["billedAmount","Supplier Billed Amount","currency",771500],["supportedAmount","Formula-Supported Amount","currency",663490],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Supplier contract library case","Material grade registry case","Index source control case","Publication date validation case","Formula price calculation case"]}),
feature("index-source-control","CFF03","Index source control","Execute index source control using supplier agreements, material grades, commodity indexes, publication dates, formula lags, floors, ceilings, freight differentials, energy surcharges, quality credits, invoices, and rebates.","Produce a governed index source control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Material Grade","text","Supplier / Material Grade · Standard Case"],["caseReference","Index source control Reference","text","CFF03-2026-001"],["billedAmount","Supplier Billed Amount","currency",771500],["supportedAmount","Formula-Supported Amount","currency",663490],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Supplier contract library case","Material grade registry case","Index source control case","Publication date validation case","Formula price calculation case"]}),
feature("publication-date-validation","CFF04","Publication date validation","Execute publication date validation using supplier agreements, material grades, commodity indexes, publication dates, formula lags, floors, ceilings, freight differentials, energy surcharges, quality credits, invoices, and rebates.","Produce a governed publication date validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Material Grade","text","Supplier / Material Grade · Standard Case"],["caseReference","Publication date validation Reference","text","CFF04-2026-001"],["billedAmount","Supplier Billed Amount","currency",771500],["supportedAmount","Formula-Supported Amount","currency",663490],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Supplier contract library case","Material grade registry case","Index source control case","Publication date validation case","Formula price calculation case"]}),
feature("formula-price-calculation","CFF05","Formula price calculation","Execute formula price calculation using supplier agreements, material grades, commodity indexes, publication dates, formula lags, floors, ceilings, freight differentials, energy surcharges, quality credits, invoices, and rebates.","Produce a governed formula price calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Material Grade","text","Supplier / Material Grade · Standard Case"],["caseReference","Formula price calculation Reference","text","CFF05-2026-001"],["billedAmount","Supplier Billed Amount","currency",771500],["supportedAmount","Formula-Supported Amount","currency",663490],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Supplier contract library case","Material grade registry case","Index source control case","Publication date validation case","Formula price calculation case"]}),
feature("lag-period-validation","CFF06","Lag period validation","Execute lag period validation using supplier agreements, material grades, commodity indexes, publication dates, formula lags, floors, ceilings, freight differentials, energy surcharges, quality credits, invoices, and rebates.","Produce a governed lag period validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Material Grade","text","Supplier / Material Grade · Standard Case"],["caseReference","Lag period validation Reference","text","CFF06-2026-001"],["billedAmount","Supplier Billed Amount","currency",771500],["supportedAmount","Formula-Supported Amount","currency",663490],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Supplier contract library case","Material grade registry case","Index source control case","Publication date validation case","Formula price calculation case"]}),
feature("floor-ceiling-control","CFF07","Floor ceiling control","Execute floor ceiling control using supplier agreements, material grades, commodity indexes, publication dates, formula lags, floors, ceilings, freight differentials, energy surcharges, quality credits, invoices, and rebates.","Produce a governed floor ceiling control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Material Grade","text","Supplier / Material Grade · Standard Case"],["caseReference","Floor ceiling control Reference","text","CFF07-2026-001"],["billedAmount","Supplier Billed Amount","currency",771500],["supportedAmount","Formula-Supported Amount","currency",663490],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Supplier contract library case","Material grade registry case","Index source control case","Publication date validation case","Formula price calculation case"]}),
feature("freight-differential-audit","CFF08","Freight differential audit","Execute freight differential audit using supplier agreements, material grades, commodity indexes, publication dates, formula lags, floors, ceilings, freight differentials, energy surcharges, quality credits, invoices, and rebates.","Produce a governed freight differential audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Material Grade","text","Supplier / Material Grade · Standard Case"],["caseReference","Freight differential audit Reference","text","CFF08-2026-001"],["billedAmount","Supplier Billed Amount","currency",771500],["supportedAmount","Formula-Supported Amount","currency",663490],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Supplier contract library case","Material grade registry case","Index source control case","Publication date validation case","Formula price calculation case"]}),
feature("energy-surcharge-validation","CFF09","Energy surcharge validation","Execute energy surcharge validation using supplier agreements, material grades, commodity indexes, publication dates, formula lags, floors, ceilings, freight differentials, energy surcharges, quality credits, invoices, and rebates.","Produce a governed energy surcharge validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Material Grade","text","Supplier / Material Grade · Standard Case"],["caseReference","Energy surcharge validation Reference","text","CFF09-2026-001"],["billedAmount","Supplier Billed Amount","currency",771500],["supportedAmount","Formula-Supported Amount","currency",663490],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Supplier contract library case","Material grade registry case","Index source control case","Publication date validation case","Formula price calculation case"]}),
feature("currency-conversion","CFF10","Currency conversion","Execute currency conversion using supplier agreements, material grades, commodity indexes, publication dates, formula lags, floors, ceilings, freight differentials, energy surcharges, quality credits, invoices, and rebates.","Produce a governed currency conversion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Material Grade","text","Supplier / Material Grade · Standard Case"],["caseReference","Currency conversion Reference","text","CFF10-2026-001"],["billedAmount","Supplier Billed Amount","currency",771500],["supportedAmount","Formula-Supported Amount","currency",663490],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Supplier contract library case","Material grade registry case","Index source control case","Publication date validation case","Formula price calculation case"]}),
feature("off-spec-quality-credits","CFF11","Off-spec quality credits","Execute off-spec quality credits using supplier agreements, material grades, commodity indexes, publication dates, formula lags, floors, ceilings, freight differentials, energy surcharges, quality credits, invoices, and rebates.","Produce a governed off-spec quality credits decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Material Grade","text","Supplier / Material Grade · Standard Case"],["caseReference","Off-spec quality credits Reference","text","CFF11-2026-001"],["billedAmount","Supplier Billed Amount","currency",771500],["supportedAmount","Formula-Supported Amount","currency",663490],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Supplier contract library case","Material grade registry case","Index source control case","Publication date validation case","Formula price calculation case"]}),
feature("volume-rebate-calculation","CFF12","Volume rebate calculation","Execute volume rebate calculation using supplier agreements, material grades, commodity indexes, publication dates, formula lags, floors, ceilings, freight differentials, energy surcharges, quality credits, invoices, and rebates.","Produce a governed volume rebate calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Material Grade","text","Supplier / Material Grade · Standard Case"],["caseReference","Volume rebate calculation Reference","text","CFF12-2026-001"],["billedAmount","Supplier Billed Amount","currency",771500],["supportedAmount","Formula-Supported Amount","currency",663490],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Supplier contract library case","Material grade registry case","Index source control case","Publication date validation case","Formula price calculation case"]}),
feature("invoice-matching","CFF13","Invoice matching","Execute invoice matching using supplier agreements, material grades, commodity indexes, publication dates, formula lags, floors, ceilings, freight differentials, energy surcharges, quality credits, invoices, and rebates.","Produce a governed invoice matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Material Grade","text","Supplier / Material Grade · Standard Case"],["caseReference","Invoice matching Reference","text","CFF13-2026-001"],["billedAmount","Supplier Billed Amount","currency",771500],["supportedAmount","Formula-Supported Amount","currency",663490],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Supplier contract library case","Material grade registry case","Index source control case","Publication date validation case","Formula price calculation case"]}),
feature("supplier-exception-workflow","CFF14","Supplier exception workflow","Execute supplier exception workflow using supplier agreements, material grades, commodity indexes, publication dates, formula lags, floors, ceilings, freight differentials, energy surcharges, quality credits, invoices, and rebates.","Produce a governed supplier exception workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Material Grade","text","Supplier / Material Grade · Standard Case"],["caseReference","Supplier exception workflow Reference","text","CFF14-2026-001"],["billedAmount","Supplier Billed Amount","currency",771500],["supportedAmount","Formula-Supported Amount","currency",663490],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Supplier contract library case","Material grade registry case","Index source control case","Publication date validation case","Formula price calculation case"]}),
feature("material-supplier-analytics","CFF15","Material supplier analytics","Execute material supplier analytics using supplier agreements, material grades, commodity indexes, publication dates, formula lags, floors, ceilings, freight differentials, energy surcharges, quality credits, invoices, and rebates.","Produce a governed material supplier analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Material Grade","text","Supplier / Material Grade · Standard Case"],["caseReference","Material supplier analytics Reference","text","CFF15-2026-001"],["billedAmount","Supplier Billed Amount","currency",771500],["supportedAmount","Formula-Supported Amount","currency",663490],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Supplier contract library case","Material grade registry case","Index source control case","Publication date validation case","Formula price calculation case"]})
]);
